"""empty message

Revision ID: 30f16317fe00
Revises: 05adb2d23810
Create Date: 2022-08-19 00:00:16.383813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f16317fe00'
down_revision = '05adb2d23810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('role_name', sa.String(), nullable=True))
    op.drop_column('teams', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('teams', 'role_name')
    # ### end Alembic commands ###
